In [1]:
import numpy as np

In [60]:
def get_empty(matrix):
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[0]):
            if matrix[i][j] == 0:
                return (i, j)

In [76]:
matrix = np.array([[1, 2, 3],
                 [4, 0, 5],
                 [7, 8, 6]])

def successors(matrix):
    i,j = get_empty(matrix)
    print(matrix)
    print("---------")
    
    if i > 0:
        print("UP")
        tmp = matrix.copy()
        tmp_value = tmp[i-1][j]
        tmp[i-1][j] = tmp[i][j]
        tmp[i][j] = tmp_value
        print(tmp)
        
    if i < matrix.shape[0] - 1:
        print("DOWN")
        tmp = matrix.copy()
        tmp_value = tmp[i+1][j]
        tmp[i+1][j] = tmp[i][j]
        tmp[i][j] = tmp_value
        print(tmp)
        
    if j > 0:
        print('LEFT')
        tmp = matrix.copy()
        tmp_value = tmp[i][j-1]
        tmp[i][j-1] = tmp[i][j]
        tmp[i][j] = tmp_value
        print(tmp)
        
    if j < matrix.shape[0] - 1:
        print("RIGHT")
        tmp = matrix.copy()
        tmp_value = tmp[i][j+1]
        tmp[i][j+1] = tmp[i][j]
        tmp[i][j] = tmp_value
        print(tmp)

    
    
successors(matrix)

[[1 2 3]
 [4 0 5]
 [7 8 6]]
---------
UP
[[1 0 3]
 [4 2 5]
 [7 8 6]]
DOWN
[[1 2 3]
 [4 8 5]
 [7 0 6]]
LEFT
[[1 2 3]
 [0 4 5]
 [7 8 6]]
RIGHT
[[1 2 3]
 [4 5 0]
 [7 8 6]]


In [79]:
matrix == np.array([[1, 2, 3],
       [4, 0, 5],
       [7, 8, 6]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
matrix